CREATE TABLE LIBROS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO Varchar(120) NOT NULL,                 
    ISBN Varchar( 20) UNIQUE NOT NULL,           
    AÑO_PUBLICACION SMALLINT,
    EDITORIAL Varchar(100),
    PRECIO decimal(6,2) NOT NULL,
    MONEDA Varchar( 20),
    NUMERO_PAGINAS int, 
    STOCK Int NOT NULL,
    FECHA_INGRESO Date,
    DISPONIBILIDAD ENUM('Si','No')
    ); 



CREATE TABLE AUTORES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_AUTOR VARCHAR( 100) NOT NULL,
    NACIONALIDAD VARCHAR ( 100),
    AÑO_DE_NACIMIENTO SMALLINT ,
    NUMERO_OBRAS INT,
    PREMIOS VARCHAR (255) NOT NULL 
);
    

CREATE TABLE LIBRO_AUTOR (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 ID_LIBRO INT NOT NULL UNIQUE,
 ID_AUTOR INT NOT NULL UNIQUE,
 PORCENTAJE_COLABORACION DECIMAL(5,2),
 FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS(ID),
 FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(ID)
        );




CREATE TABLE CATEGORIAS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR( 100),
DESCRIPCION VARCHAR (255),
POPULARIDAD INT (11)
);




CREATE TABLE LIBRO_CATEGORIA(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_LIBRO INT,
    ID_CATEGORIA INT,
    NIVEL_IMPORTANCIA INT (11),
    FOREIGN KEY ( ID_LIBRO) REFERENCES LIBROS(ID),
    FOREIGN KEY ( ID_CATEGORIA) REFERENCES CATEGORIAS(ID)
    );




CREATE TABLE PERSONAS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100 ),
EMAIL VARCHAR(100),
TELEFONO Varchar (25),
FECHA_REGISTRO datetime,
CUOTA_MENSUAL decimal( 5,2),
ACTIVO enum ('Si','No')
);





CREATE TABLE PERSONAS_LIBROS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PERSONA INT,
    ID_LIBRO INT,
FECHA_PRESTAMO DATE,
FECHA_DEVOLUCION DATE NULL,
MORA INT,
    FOREIGN KEY ( ID_PERSONA) REFERENCES PERSONAS(ID),
    FOREIGN KEY ( ID_LIBRO) REFERENCES LIBROS(ID)
);



INSERT INTO LIBROS (ID, TITULO, ISBN, AÑO_PUBLICACION, EDITORIAL, PRECIO,MONEDA, NUMERO_PAGINAS, STOCK, FECHA_INGRESO, DISPONIBILIDAD) VALUES 
(NULL,"LA_DANZA_DE_LOS_TULIPANES",2899465792132,2019,"PLAZA_Y_JANES",14.45,"EUROS",420,3,"2025-10-29","SI"), 
(NULL,"DON_QUIJOTE_DE_LA_MANCHA",9788491051235, 1600, "ESPASA", 22.50,"EUROS" ,1500, 5,"2005-11-28","SI"),
(NULL,"LA_MADRE",0987653891980,2018,"PLANETA",16.98,"EUROS",295,7,"2020-08-10","SI"),
(NULL,"EL_PRINCIPITO", "9780156013987", 1943, "REYNAL_Y_HITCHCOCK", 12.99, "EURO", 96, 10, "2025-12-07", "SI"),
(NULL,'BREVE_HISTORIA_DEL_TIEMPO', '9780553380163', 1988, 'BANTAM_BOOKS', 19.50, 'EUR', 212, 2, '2025-12-07', 'SI');


INSERT INTO AUTORES(ID,NOMBRE_AUTOR,NACIONALIDAD,AÑO_DE_NACIMIENTO,NUMERO_OBRAS,PREMIOS) VALUES 
(NULL, 'Ibon_Martin', 'Española', 1976, 10, 'Premio_Euskadi_de_Literatura'), 
(NULL, 'Miguel_de_Cervantes', 'Española', 1547, 30, 'Premio_Cervantes (postumo,reconocimiento_historico)'), 
(NULL, 'Fiona_Barton', 'Britanica', 1957, 20, 'Premio_Nacional_de_la_prensa_Britanica'), 
(NULL, 'Antoine_de_Saint_Exupery', 'Francesa', 1900, 15, 'Gran_Premio_de_la_Academia_Francesa'), 
(NULL, 'Stephen_Hawking', 'Britanica', 1942, 15, 'Wolf_Prize_in_Physics');


INSERT INTO CATEGORIAS (ID, NOMBRE_CATEGORIA,DESCRIPCION,POPULARIDAD) VALUES 
(NULL, 'Novela', 'Libros de narrativa extensa.Trata distintos temas.Entretenimiento', 10), 
(NULL, 'Clasicos', 'Obras literarias de todos los tiempos, clasicos-antiguos,clasicos-modernos,etc', 6),
(NULL, 'Historia', 'Libros sobre hechos y personajes historicos', 9), 
(NULL, 'Ciencia', 'Obras de divulgacion cientifica y tecnica', 7),
(NULL, 'Infantil', 'Lecturas dirigidas a niños y jovenes', 9)


INSERT INTO PERSONAS (ID, NOMBRE, EMAIL, TELEFONO, FECHA_REGISTRO, CUOTA_MENSUAL,ACTIVO) VALUES 
(NULL, 'Juan_Garcia_Bellota', 'juan.garcia@gmail.com', '+ 34 600123456', '2022-12-07', 25.50, 'NO'), 
(NULL, 'Maria_Lopez_peinado', 'maria.lopez@gmail.com', '+ 34 611987654', '2018-07-07', 30.00, 'SI'),
(NULL, 'Carlos_Fernandez_Carballo', 'carlos.fernandez@hotmail.com', ' +34 622334455', '2008-04-28', 18.75, 'SI'),
(NULL, 'Lucia_Martinez_Morillo', 'lucia.martinez@cloud.com', ' + 34 633445566', '2025-02-01', 27.00, 'NO')
TABLA AUTORES


INSERT INTO LIBRO_AUTOR (ID, ID_LIBRO, ID_AUTOR, PORCENTAJE_COLABORACION) VALUES
 (NULL, 1, 1, 100.00),
(NULL, 2, 2, 100.00), 
(NULL, 3, 3, 100.00),
(NULL, 4, 4, 100.00),  
(NULL,5,5,100.00)



INSERT INTO LIBRO_CATEGORIA(ID,ID_LIBRO,ID_CATEGORIA,NIVEL_IMPORTANCIA)VALUES
(NULL,1,2,4),
(NULL,2,2,11),
(NULL,3,1,4),
(NULL,4,5,8),
(NULL,5,4,7)

INSERT INTO PERSONAS_LIBROS(ID,ID_PERSONA,ID_LIBRO,FECHA_PRESTAMO,FECHA_DEVOLUCION,MORA)VALUES
(NULL,1,1,'2023-08-21','2023-10-10',15),
(NULL,2,2,'2025-10-12',’0000-00-00’,0),
(NULL,3,3,'2018-06-01',’0000-00-00’,0),
(NULL,4,4,'2024-12-04','2025-12-04',365)


CREATE VIEW vista_libros_autores AS
SELECT l.*,a.NOMBRE_AUTOR
FROM LIBROS l INNER JOIN LIBRO_AUTOR la 
ON la.ID_LIBRO = l.ID
INNER JOIN AUTORES a ON a.ID = la.ID_AUTOR;





CREATE VIEW vista_prestamos_activo3 AS
SELECT  P.NOMBRE,L.TITULO,P.ACTIVO
FROM PERSONAS P INNER JOIN personas_libros PT ON P.ID = PT.ID INNER JOIN LIBROS L ON PT.ID = L.ID
WHERE FECHA_DEVOLUCION = "0000-00-00";




CREATE VIEW NOMBRE_AUTOR_NUMERO_OBRAS AS
SELECT NOMBRE_AUTOR,NUMERO_OBRAS
FROM AUTORES



create view Utilizacion_LIKE AS
SELECT * 
FROM AUTORES
WHERE PREMIOS  LIKE  '%post%'



create view Utilizacion_LIKE2 AS
SELECT * 
FROM CATEGORIAS
WHERE NOMBRE_CATEGORIA   LIKE  'CLA%'







CREATE VIEW AÑO_PUBLICACION AS
SELECT * 
FROM libros
WHERE AÑO_PUBLICACION >= 2015 AND AÑO_PUBLICACION <= 2025






CREATE VIEW AÑO_PUBLICACIONES AS
SELECT * 
FROM libros
WHERE AÑO_PUBLICACION BETWEEN 2015 AND 2025




CREATE VIEW CONSULTA_VALOR1 AS
SELECT * 
FROM categorias
WHERE NOMBRE_CATEGORIA= "CLASICO" OR NOMBRE_CATEGORIA=  "CIENCIA"





CREATE VIEW CONSULTA_VALOR3 AS
SELECT * 
FROM categorias
WHERE NOMBRE_CATEGORIA IN ("infantil","novela")




create view Utilizacion_LIKE3 AS
SELECT * 
FROM AUTORES
WHERE NACIONALIDAD  LIKE  '%CA'





create view Utilizacion_LIKE4 AS
SELECT * 
FROM PERSONAS
WHERE TELEFONO  LIKE  ' +34 622%'



